package com.g.laurent.alitic

const val PAGE = "PAGE"
const val TAG_SCHEDULE_DIALOG = "schedule_dialog_fragment"
const val TAG_FOOD_SETTINGS_DIALOG = "food_settings_dialog_fragment"
const val TAG_EVENT_SETTINGS_DIALOG = "event_settings_dialog_fragment"
const val LIST_TO_SAVE = "list to save"
const val TYPE_DISPLAY = "typedisplay"
const val DAY_ARGS = "day_args"
const val MONTH_ARGS = "month_args"
const val YEAR_ARGS = "year_args"
const val LIST_EVENT_TYPES = "list_eventTypes"
const val STAT_TYPE = "stat_type"
const val NAME_USER = "name_user"
const val SHAREDPREF = "sharedpref_alitic"
const val PERMISSION_WRITE_STORAGE = 105
const val FOOD_PARAMS = "food_params"
const val EVENT_TYPE_PARAMS = "event_type_params"
const val DAY:Long = 24*60*60*1000
const val POPULATE_DATABASE = "POPULATE_DATABASE"
const val SHARED_PREF_SWIDTH = "sWidth"
const val SHARED_PREF_SHEIGHT = "sHeight"
const val SHARED_PREF_DWIDTH = "dWidth"
const val SHARED_PREF_DHEIGHT = "dHeight"
const val SHARED_PREF_GRID_DHEIGHT = "grid_height"
const val DELETE = "DELETE"
const val UNSELECT = "UNSELECT"
const val SELECT = "SELECT"
const val TYPEDISPLAY = "typeDisplay"
const val TIMELINE_FRAGMENT = "Timeline_fragment"
const val CHRONO_FRAGMENT = "Chrono_fragment"
const val OPACITY_LIMIT = 0.25f
const val DURATION_MOVE_CAMERA = 3000.toLong()
const val DURATION_MIN_ANALYSIS_IN_DAYS = 10